CREATE DATABASE recipe;

USE recipe;

CREATE TABLE users(
id INTEGER NOT NULL AUTO_INCREMENT PRIMARY KEY,
user VARCHAR(255) NOT NULL,
user_hash VARCHAR(255) NOT NULL
);

CREATE TABLE ingredients(
id INTEGER NOT NULL AUTO_INCREMENT PRIMARY KEY,
ingredient VARCHAR(255) NOT NULL,
quantity INTEGER NOT NULL,
unit VARCHAR (100) NOT NULL,
user INTEGER,
FOREIGN KEY (user) REFERENCES users(id)
);
