CREATE DATABASE recipe;

USE recipe;

CREATE TABLE ingredients(
id INTEGER NOT NULL AUTO_INCREMENT PRIMARY KEY,
ingredient VARCHAR(255) NOT NULL,
quantity INTEGER NOT NULL,
unit VARCHAR(100) NOT NULL
);

